config/routes.rb
SlowestLab::Application.routes.draw do
  root :to => "dashboard#show"
  resources :users, :only => [:create, :show, :index] do
    resource :follows, :only => [:create, :destroy]
  end
  resources :sessions, :only => [:create, :new]
  delete '/sessions', :to => 'sessions#destroy', :as => :signout
  resources :venues, :only => [:show, :index]
  resources :shows, :only => [:show, :index] do
    resource :attendances, :only => [:create, :destroy]

  end
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :user
  belongs_to :show, {includes :venue}

  validates_uniqueness_of :user_id, :scope => [:show_id]
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :followed, :class_name => 'User'
  belongs_to :follower, :class_name => 'User'

  validates_uniqueness_of :followed_id, :scope => [:follower_id]
end

app/models/show.rb
class Show < ActiveRecord::Base
  belongs_to :user
  belongs_to :venue
  has_many :attendances
  has_many :users, :through => :attendances
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  before_validation { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates_uniqueness_of :email

  has_many :inward_follows, :class_name => 'Follow', :foreign_key => 'followed_id'
  has_many :outward_follows, :class_name => 'Follow', :foreign_key => 'follower_id'

  has_many :followers, :through => :inward_follows, :source => :follower
  has_many :followeds, :through => :outward_follows, :source => :followed

  has_many :attendances, -> {includes :show}

  def avatar
    a = read_attribute(:avatar)
    unless a
      a = "http://robohash.org/#{SecureRandom.urlsafe_base64(5)}"
      write_attribute(:avatar, a)
    end
    a
  end

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  belongs_to :user
  has_many :shows
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  
  
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def create
    current_user.attendances.create!(:show_id => params[:show_id])
    redirect_to show_path(params[:show_id])
  end
  def destroy
    current_user.attendances.find_by(:show_id => params[:show_id]
      ).destroy
    redirect_to show_path(params[:show_id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    if !signed_in?
      redirect_to new_session_path
    else
      @attendances = current_user.attendances.distinct

      #This is the worst:
    @followed_attendances = []
    current_user.followeds.map{|u| u.attendances}.each do |a|
      @followed_attendances += a
    end
    @followed_attendances.sort_by!{|a| a.show.date}
      
    #  @followed_attendances = User.includes(followeds: [attendances: [{show: :venue}, :user]]).find(current_user.id)

  #    @followed_attendances = current_user.followeds.includes(:attendances)

    end
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def create
    current_user.outward_follows.create!(:followed_id => params[:user_id])
    redirect_to user_path(params[:user_id])
  end
  def destroy
    current_user.outward_follows.find_by(:followed_id => params[:user_id]
      ).destroy
    redirect_to user_path(params[:user_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user=User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Sign the user in and redirect to the user's show page.
      sign_in user
      redirect_to root_path
    else
      # Create an error message and re-render the signin form.
      flash.now[:error]='Invalid email/password combination'
      @user = User.new
      render 'new'
    end
  end

  def destroy
      sign_out
      redirect_to root_url
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def show
    @show = Show.find(params[:id])
    if signed_in?
      @attending_this = current_user.attendances.where(
        :show_id => @show.id).exists?
    end
  end
  def index
    @shows = Show.all.includes(:attendances).limit(1000)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    up = params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
    user = User.new(up)
    if user.save
      flash[:success] = "Welcome to the Slowest app!"
      sign_in user
      redirect_to root_path
    else
      flash[:error] = "Something went wrong with your signup."
      redirect_to new_session_path
    end
  end
  
  def show
    @user = User.find(params[:id])
    if signed_in?
      @following = current_user.outward_follows.where(
        :followed_id => @user.id).exists?.includes(:attendances, :shows, :venues)
    end
  end

  def index
    @users = User.all
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  def show
    @venue = Venue.find(params[:id])
  end
  def index
    @venues = Venue.all.includes(:shows)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
# signs in supplied user, called from SessionController
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    # current_user is avilable in controllers and views!
    # This is an is an assignment, which we must define - see below
    # note that next line is a call to setter 'def current_user=(user)' below
    current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  # Authorization: signed_in_user is called in a before_filter
  # callback in each controller, see books/ingredients/recipe controllers
  # Ensures access to create/edit functions on if signed in.
  def signed_in_user
    unless signed_in?
      # If not signed in, save current location in session object
      # to be able to redirect after successful sign in.
      session[:return_to] = request.url
      # prompt sign in page
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  # signs out user by deleting @current_user and session cookie
  def sign_out
    @current_user = nil
    cookies.delete(:remember_token)
  end

  # Getter and setter for @current_user
  def current_user=(user)
    @current_user = user
  end

  # if current_user doesn't exist, check session cookie for user session
  # If exists, get the user record that belongs to that session.
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
end

app/views/attendances/_attendance.html.erb
<div>
  <p class="_attendance">
    <%= link_to attendance.show do %>
      <%= attendance.show.title %>
      on
      <%= attendance.show.date.in_time_zone("Pacific Time (US & Canada)") %>
    <% end %>
    At:
    <%= link_to attendance.show.venue do %>
      <%= attendance.show.venue.name %>
    <% end %>
  </p>
</div>

app/views/attendances/_attendance_with_user.html.erb
<div>
  <p class="_attendence_user">
  <%= image_tag attendance.user.avatar, :class => 'avatar' %>
    <%= link_to attendance.user do %>
      <%= attendance.user.name %>
    <% end %>
     will be at:
    <%= link_to attendance.show do %>
      <%= attendance.show.title %>
      on
      <%= attendance.show.date.in_time_zone("Pacific Time (US & Canada)") %>
    <% end %>
    At:
    <%= link_to attendance.show.venue do %>
      <%= attendance.show.venue.name %>
    <% end %>
  </p>
</div>

app/views/dashboard/show.html.erb
<div>
<h1>Shows you are attending:</h1>
<ul>
  <%= render @attendances %>
</ul>
<h1>Shows the people you are following are attending</h1>
<ul>
  <%= render :partial => 'attendances/attendance_with_user',
       :collection => @followed_attendances, :as => 'attendance'%>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SlowestLab</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
  <div class="navbar-header pull-left">
    <a class="navbar-brand" href="/">The Slowest App</a>
  </div>
  <div class="navbar-header pull-right">
    <ul class="nav navbar-nav">
      <% if signed_in? %>
        <li>
          <%= link_to "My dashboard", root_path %>
        </li>
        <li>
          <%= link_to "Sign out", signout_path, method: "delete" %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign in or sign up", new_session_path %>
        </li>
      <% end %>
      <li><%= link_to('Users', users_path) %></li>
      <li><%= link_to('Venues', venues_path) %></li>
      <li><%= link_to('Shows', shows_path) %></li>
    </ul>
  </div>
  </div>
</nav>
        <%flash.each do|key,value|%>
                <div class="alert alert-<%=key%>"> <%=value%> </div>
        <%end%>
<%= yield %>
</div>
</body>
</html>

app/views/shows/_show.html.erb
<h4>  
    <%= link_to show do %>
      <%= show.title %>
      on
      <%= show.date.in_time_zone("Pacific Time (US & Canada)") %>
    <% end %>
</h4>
<ul>
  <%= render show.users %>
</ul>

app/views/shows/index.html.erb
<ul>
  <%= render @shows %>
</ul>

app/views/shows/show.html.erb
<h1> <%= @show.title %> </h1>

<h2> At <%= link_to(@show.venue) {@show.venue.name} %> </h2>

<p><%= @show.description %></p>
<p>
  <% if signed_in? %>
    <% if @attending_this %>

      <%= button_to("Cancel attending this show",show_attendances_path(@show.id), :method => :delete, :class => 'btn btn-danger') %>
    <% else %>
      <%= button_to("Attend this show",show_attendances_path(@show.id), :class => 'btn btn-success') %>
    <% end %>
  <% end %>
</p>
<h3>Users attending this show:</h3> 
<%= render @show.users %>

app/views/users/_user.html.erb
<p>
  <%= link_to user.name, user_path(user)%>
</p>

app/views/users/_user_with_shows.html.erb
<div>
<p>
  <%= link_to user do %>
    <%= user.name %>
  <% end %>
</p>
<ul><%= render user.attendances %></ul>
</div>

app/views/users/index.html.erb
<ul>
  <%= render :partial => 'user_with_shows', :collection => @users, :as => 'user'%>
</ul>

app/views/users/show.html.erb
<h1> <%= @user.name %> </h1>
<span>
  <% if signed_in? %>
    <% if @following %>

      <%= button_to("Stop following this user",user_follows_path(@user.id), :method => :delete, :class => 'btn btn-danger') %>
    <% else %>
      <%= button_to("Follow this user",user_follows_path(@user.id), :class => 'btn btn-success') %>
    <% end %>
  <% end %>
</span>
<h2>
<p>
follows <%= @user.followeds.size %> users and is followed by
<%= @user.followers.size %> users.
</p>

<ul>
<%= render @user.attendances %>
</ul></h2>

app/views/venues/_venue.html.erb
<%= link_to venue do %>
  <%= venue.name %>
<% end %>
<ul>
<%= render venue.shows %>
</ul>

app/views/venues/index.html.erb
<ul>
  <%= render @venues%>
</ul>

app/views/venues/show.html.erb
<h1><%= @venue.name %> </h1>
<h2> <%= @venue.description %> </h2>

<h3> Upcoming shows: </h3>
<%= render @venue.shows %>